### ISSUE TITLE
Issue regarding image links for angular project

### ISSUE THREAD

**Issue by darthhomme** [darthhomme/thegreylady#1]
I just want to make the images appear, not anything else.

**Comment by darthhomme** [comment]
What I tried so far was to use an embed code so I can use the web_url for my articles to create a UI friendly image link.

**Comment by Avizacherman** [comment]
Can you post a copy of your error and your code here?

**Comment by darthhomme** [comment]
[cid:9a8245af-df81-44d4-98dd-4386d47394d1]

This looks weird. The black lines running vertical to the left. I just want to get rid of them. I'm using a third party script for the embedded links. Wondering if there was a better way.
